name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
        working-directory: frontend
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy preview_name --expires 1d
          working-directory: frontend
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to Firebase others
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore, functions, storage, remoteconfig
          working-directory: frontend
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
